# Worlds in which the pets should be disabled
worlds-disabled:
  - world_the_nether
  - world_the_end

pets:
  chicken:
    price: 100
    enabled: true
  cat:
    price: 100
    enabled: true
  dog:
    price: 100
    enabled: true
  slime:
    price: 100
    enabled: true
  squid:
    price: 100
    enabled: true
  rabbit:
    price: 100
    enabled: true

# The radius of the pets' effects
pet-radius: 10
# Determines if a pet can take damage
pet-invulnerable: true
# Determines if the pets should receive a random colored name
random-color: true
# To change the language, please provide an existing language file in the 'lang' folder
language-file: US_en.lang