# Worlds in which the pets should be disabled (default: 'world_the_nether', 'world_the_end')
worlds-disabled:
  - world_the_nether
  - world_the_end

pets:
  ChickenPet:
    price: 500
    enabled: true
  CatPet:
    price: 1500
    enabled: true
  WolfPet:
    price: 1500
    enabled: true
  SlimePet:
    price: 800
    enabled: true
  RabbitPet:
    price: 1000
    enabled: true
  MushroomCowPet:
    price: 1200
    enabled: true

# Permission required to access the admin commands (default: pets.admin)
admin-permission: pets.admin
# The radius of the pets' effects (default: 10)
pet-radius: 10
# Determines if a pet can take damage (default: true)
pet-invulnerable: true
# Determines if the pets should receive a random colored name (default: true)
random-color: true
# To change the language, please provide an existing language file in the 'languages' folder (default: en_US)
language-file: en_US

# Enables/Disables mysql support (default: false)
mysql-enabled: false

mysql-hostname: 'localhost'
mysql-username: 'root'
mysql-password: ''
mysql-database: ''
mysql-port: 3306