# Worlds in which the pets should be disabled
worlds-disabled:
  - world_the_nether
  - world_the_end

pets:
  ChickenPet:
    price: 100
    enabled: true
  CatPet:
    price: 100
    enabled: true
  DogPet:
    price: 100
    enabled: true
  SlimePet:
    price: 100
    enabled: true
  SquidPet:
    price: 100
    enabled: true
  RabbitPet:
    price: 100
    enabled: true

# The radius of the pets' effects
pet-radius: 10
# Determines if a pet can take damage
pet-invulnerable: true
# Determines if the pets should receive a random colored name
random-color: true
# To change the language, please provide an existing language file in the 'languages' folder
language-file: US_en